server.port=${PORT:8091}
server.address=0.0.0.0
spring.data.mongodb.uri=mongodb+srv://slmdb:mona46@cluster0.iqi5ljb.mongodb.net/slmdb?retryWrites=true&w=majority

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
